INFO:114:2025-09-14 11:12:03,620:[DatabaseManager.get_connection]=>[get_connection] Starting Execution
INFO:114:2025-09-14 11:12:03,620:[DatabaseManager.get_path]=>[get_path] Starting Execution
INFO:122:2025-09-14 11:12:03,621:[DatabaseManager.get_path]=>[get_path] Execution of completed in 0.11 ms
INFO:122:2025-09-14 11:12:03,629:[DatabaseManager.get_connection]=>[get_connection] Execution of completed in 9.30 ms
INFO:54:2025-09-14 11:12:03,630:[BaseTemplates.create]=>[create] Starting Execution
INFO:54:2025-09-14 11:12:03,630:[DatabaseManager.insert]=>[insert] Starting Execution
INFO:76:2025-09-14 11:12:03,660:Execution of [DatabaseManager.insert]=>[insert] failed
ERROR:79:2025-09-14 11:12:03,661:[DatabaseManager.insert]=>[insert] => table students has no column named emp_id
Traceback (most recent call last):
  File "/media/elsonbaty/My/Projects/Sonbati_Academey/core/log_utils.py", line 58, in wrappers
    results = func(*args, **kwd)
              ^^^^^^^^^^^^^^^^^^
  File "/media/elsonbaty/My/Projects/Sonbati_Academey/modules/database_manager.py", line 141, in insert
    curr.execute(query, tuple(data.values()))
sqlite3.OperationalError: table students has no column named emp_id
INFO:64:2025-09-14 11:12:03,669:[BaseTemplates.create]=>[create] Execution of completed in 38.97 ms
